"""
app_bracket.py — Flask app for the top-64 single-elimination bracket.

Run locally with:
    python app_bracket.py

Then open http://127.0.0.1:5000

Differences from app_top10.py:
  - No Elo system or similarity models
  - Voting is ballot-based: user votes all of today's matchups, then submits once
  - One ballot per IP per round (tracked via bracket_votes table)
  - Bracket structure loaded from bracket.json (generated by generate_bracket.py)
  - bracket_results table records final tallies after advance_bracket.py runs
  - bracket_state table tracks current day
"""

import json
import os
import random
import uuid
from contextlib import contextmanager
from datetime import datetime, timezone

import pandas as pd
import psycopg2
from psycopg2.pool import ThreadedConnectionPool
from dotenv import load_dotenv
from flask import Flask, jsonify, render_template, request, session

load_dotenv()

import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from parse_data import load_processed_cards

# ── App setup ──────────────────────────────────────────────────────────────────

app = Flask(__name__)
app.secret_key = os.urandom(24)

DATABASE_URL = os.environ.get('DATABASE_URL', '').replace('postgres://', 'postgresql://', 1)
BRACKET_JSON = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'bracket.json')
STATS_TOKEN  = os.environ.get('STATS_TOKEN', 'bracketstats')

_pool = None


@contextmanager
def _get_db():
    conn = _pool.getconn()
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        _pool.putconn(conn)


# ── Database ───────────────────────────────────────────────────────────────────

def _init_pool():
    global _pool
    if not DATABASE_URL:
        raise RuntimeError('DATABASE_URL environment variable is not set.')
    _pool = ThreadedConnectionPool(minconn=1, maxconn=10, dsn=DATABASE_URL)


def init_db():
    _init_pool()
    with _get_db() as conn:
        cur = conn.cursor()

        # One row per individual vote (one IP may cast multiple matchup votes per round)
        cur.execute('''
            CREATE TABLE IF NOT EXISTS bracket_votes (
                id         SERIAL  PRIMARY KEY,
                ballot_id  TEXT    NOT NULL,
                timestamp  TEXT    NOT NULL,
                ip_address TEXT    NOT NULL,
                round      INTEGER NOT NULL,
                day        INTEGER NOT NULL,
                matchup_id INTEGER NOT NULL,
                card_a     TEXT    NOT NULL,
                card_b     TEXT    NOT NULL,
                chosen     TEXT,
                device     TEXT
            )
        ''')
        # Migrate existing tables: add columns added after initial deploy
        for col, defn in [
            ('ballot_id', "TEXT NOT NULL DEFAULT ''"),
            ('card_a',    "TEXT NOT NULL DEFAULT ''"),
            ('card_b',    "TEXT NOT NULL DEFAULT ''"),
        ]:
            cur.execute(f'ALTER TABLE bracket_votes ADD COLUMN IF NOT EXISTS {col} {defn}')
        cur.execute('ALTER TABLE bracket_votes ALTER COLUMN chosen DROP NOT NULL')

        # Final tallies written by advance_bracket.py after voting closes
        cur.execute('''
            CREATE TABLE IF NOT EXISTS bracket_results (
                matchup_id    INTEGER PRIMARY KEY,
                round         INTEGER NOT NULL,
                day           INTEGER NOT NULL,
                bracket_date  TEXT,
                card_a        TEXT    NOT NULL,
                card_b        TEXT    NOT NULL,
                seed_a        INTEGER,
                seed_b        INTEGER,
                votes_a       INTEGER NOT NULL DEFAULT 0,
                votes_b       INTEGER NOT NULL DEFAULT 0,
                winner        TEXT    NOT NULL,
                winner_seed   INTEGER,
                closed_at     TEXT    NOT NULL
            )
        ''')
        cur.execute('ALTER TABLE bracket_results ADD COLUMN IF NOT EXISTS bracket_date TEXT')

        # Single-row state table
        cur.execute('''
            CREATE TABLE IF NOT EXISTS bracket_state (
                id          INTEGER PRIMARY KEY DEFAULT 1,
                current_day INTEGER NOT NULL DEFAULT 1
            )
        ''')
        cur.execute('''
            INSERT INTO bracket_state (id, current_day)
            VALUES (1, 1)
            ON CONFLICT DO NOTHING
        ''')


def _get_current_day():
    with _get_db() as conn:
        cur = conn.cursor()
        cur.execute('SELECT current_day FROM bracket_state WHERE id = 1')
        row = cur.fetchone()
        return row[0] if row else 1


def _has_voted(ip, day):
    with _get_db() as conn:
        cur = conn.cursor()
        cur.execute(
            'SELECT 1 FROM bracket_votes WHERE ip_address = %s AND day = %s LIMIT 1',
            (ip, day),
        )
        return cur.fetchone() is not None


def _log_votes(ip, day, round_, vote_pairs, device, ballot_id):
    """vote_pairs: list of (matchup_id, chosen_name, card_a, card_b)"""
    ts = datetime.now(timezone.utc).isoformat()
    with _get_db() as conn:
        cur = conn.cursor()
        for mid, chosen, card_a, card_b in vote_pairs:
            cur.execute(
                'INSERT INTO bracket_votes '
                '(ballot_id, timestamp, ip_address, round, day, matchup_id, card_a, card_b, chosen, device) '
                'VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)',
                (ballot_id, ts, ip, round_, day, mid, card_a, card_b, chosen, device),
            )


def _get_results():
    with _get_db() as conn:
        cur = conn.cursor()
        cur.execute(
            'SELECT matchup_id, card_a, card_b, seed_a, seed_b, '
            '       votes_a, votes_b, winner, winner_seed '
            'FROM bracket_results'
        )
        rows = cur.fetchall()
    return {
        mid: {
            'card_a': ca, 'card_b': cb, 'seed_a': sa, 'seed_b': sb,
            'votes_a': va, 'votes_b': vb, 'winner': w, 'winner_seed': ws,
        }
        for mid, ca, cb, sa, sb, va, vb, w, ws in rows
    }


def _client_ip():
    # CF-Connecting-IP is set by Cloudflare to the true client IP and cannot be spoofed via XFF
    cf = request.headers.get('CF-Connecting-IP', '').strip()
    if cf:
        return cf
    xff = request.headers.get('X-Forwarded-For', '')
    return xff.split(',')[0].strip() if xff else request.remote_addr


def _detect_device(ua):
    ua = (ua or '').lower()
    return 'mobile' if any(t in ua for t in ('mobile', 'android', 'iphone', 'ipad')) else 'desktop'


def log_page_view(page):
    try:
        ts  = datetime.now(timezone.utc).isoformat()
        ip  = _client_ip()
        sid = session.get('session_id')
        dev = _detect_device(request.headers.get('User-Agent', ''))
        with _get_db() as conn:
            cur = conn.cursor()
            cur.execute(
                'INSERT INTO page_views (timestamp, page, ip_address, session_id, device) '
                'VALUES (%s, %s, %s, %s, %s)',
                (ts, page, ip, sid, dev),
            )
    except Exception:
        pass


# ── Card data ──────────────────────────────────────────────────────────────────

DOUBLE_FACED_LAYOUTS               = {'transform', 'modal_dfc'}
SIDEWAYS_TYPES                     = {'Battle', 'Room'}
SIDEWAYS_LAYOUTS                   = {'split'}
SIDEWAYS_LAYOUT_KEYWORD_EXCLUSIONS = {'Aftermath'}

IMAGE_OVERRIDES = {
    'Sothera, the Supervoid': 'https://cards.scryfall.io/large/front/e/9/e99d6fc0-dcf2-4b25-81c2-02c230a36246.jpg',
    'The Wandering Emperor':  'https://cards.scryfall.io/large/front/f/a/fab2d8a9-ab4c-4225-a570-22636293c17d.jpg',
}

print('Loading bracket.json...')
with open(BRACKET_JSON, encoding='utf-8') as _f:
    _bracket = json.load(_f)

_matchup_by_id = {m['id']: m for m in _bracket['matchups']}
_cards_by_name = {c['name']: c for c in _bracket['cards']}
_all_names     = set(_cards_by_name)

print('Loading card metadata...')
_df   = load_processed_cards()
_meta = _df[_df['name'].isin(_all_names)].drop_duplicates('name').set_index('name')


def _meta_get(name, col, default=''):
    try:
        v = _meta.at[name, col]
        return default if (isinstance(v, float) and pd.isna(v)) else v
    except KeyError:
        return default


def _is_sideways(name):
    layout    = str(_meta_get(name, 'layout'))
    type_line = str(_meta_get(name, 'type_line'))
    kw        = _meta_get(name, 'keywords', None)
    kw_list   = list(kw) if kw is not None and not isinstance(kw, float) else []
    vintage   = _meta_get(name, 'legal_vintage', 'not_legal') in {'legal', 'restricted'}
    if any(t in type_line for t in SIDEWAYS_TYPES):
        return True
    if layout in SIDEWAYS_LAYOUTS and vintage and not any(k in kw_list for k in SIDEWAYS_LAYOUT_KEYWORD_EXCLUSIONS):
        return True
    return False


_card_info_cache = {}


def _get_card_info(name):
    if name in _card_info_cache:
        return _card_info_cache[name]
    card = _cards_by_name.get(name, {})
    img_front = IMAGE_OVERRIDES.get(name) or card.get('img_front')
    img_back  = card.get('img_back')
    if isinstance(img_front, float): img_front = None
    if isinstance(img_back,  float): img_back  = None
    info = {
        'img_front':   img_front,
        'img_back':    img_back,
        'is_sideways': _is_sideways(name),
        'set_name':    card.get('set_name', ''),
        'year':        card.get('year') or '',
        'seed':        card.get('seed'),
    }
    _card_info_cache[name] = info
    return info


# ── Matchup resolution ─────────────────────────────────────────────────────────

def _resolve_card(matchup, side, results_by_id):
    """Return (name, seed) for 'a' or 'b' side, walking feeder chain for R2+ matchups."""
    if matchup['round'] == 1:
        return matchup[f'name_{side}'], matchup[f'seed_{side}']
    feeder_id = matchup[f'feeder_{side}']
    res = results_by_id.get(feeder_id)
    if res:
        return res['winner'], res['winner_seed']
    return None, None


def _build_matchup_context(matchup, results_by_id, flip):
    """
    Return a template-ready dict for one matchup.
    flip=True swaps which card appears on the left vs right.
    Seeds are intentionally omitted from the returned dict.
    """
    name_a, _ = _resolve_card(matchup, 'a', results_by_id)
    name_b, _ = _resolve_card(matchup, 'b', results_by_id)

    info_a = _get_card_info(name_a) if name_a else {}
    info_b = _get_card_info(name_b) if name_b else {}

    if flip:
        left_name,  right_name  = name_b,  name_a
        left_info,  right_info  = info_b,  info_a
    else:
        left_name,  right_name  = name_a,  name_b
        left_info,  right_info  = info_a,  info_b

    return {
        'id':            matchup['id'],
        'round':         matchup['round'],
        'left_name':     left_name,
        'left_img_front':left_info.get('img_front'),
        'left_img_back': left_info.get('img_back'),
        'left_sideways': left_info.get('is_sideways', False),
        'left_set':      left_info.get('set_name', ''),
        'left_year':     left_info.get('year', ''),
        'right_name':    right_name,
        'right_img_front':right_info.get('img_front'),
        'right_img_back': right_info.get('img_back'),
        'right_sideways': right_info.get('is_sideways', False),
        'right_set':      right_info.get('set_name', ''),
        'right_year':     right_info.get('year', ''),
    }


# ── Bracket page display order ─────────────────────────────────────────────────

def _shuffle_bracket_tree(r1_matchups, rng):
    """
    Recursively shuffle the bracket display order by randomly swapping subtrees
    at each level.  This preserves the tree structure: consecutive pairs in the
    output still correspond to the same R2 matchup, consecutive pairs-of-pairs
    to the same R3 matchup, etc.

    r1_matchups: list of R1 matchup dicts in natural bracket order.
    Returns: flat list of R1 matchup IDs in shuffled display order.
    """
    if len(r1_matchups) == 1:
        return [r1_matchups[0]['id']]

    if len(r1_matchups) == 2:
        a, b = r1_matchups[0]['id'], r1_matchups[1]['id']
        return [b, a] if rng.random() < 0.5 else [a, b]

    mid   = len(r1_matchups) // 2
    left  = _shuffle_bracket_tree(r1_matchups[:mid], rng)
    right = _shuffle_bracket_tree(r1_matchups[mid:], rng)
    return (right + left) if rng.random() < 0.5 else (left + right)


def _build_bracket_display(results_by_id):
    """
    Return a list of rounds, each round being an ordered list of enriched matchup dicts
    ready for the bracket page template.  Uses the pre-computed display order and flips.
    """
    # Build feeder-set → matchup lookup for R2+ matchups
    feeder_lookup = {}
    for m in _bracket['matchups']:
        if m['round'] > 1:
            feeder_lookup[frozenset({m['feeder_a'], m['feeder_b']})] = m

    # Derive ordered matchup lists for each round from the shuffled R1 order
    r1_by_id = {m['id']: m for m in _bracket['matchups'] if m['round'] == 1}
    ordered_by_round = [[r1_by_id[mid] for mid in _display_r1_order]]

    prev = ordered_by_round[0]
    for _ in range(2, _bracket['num_rounds'] + 1):
        cur_round = []
        for i in range(0, len(prev), 2):
            key = frozenset({prev[i]['id'], prev[i + 1]['id']})
            m   = feeder_lookup.get(key)
            if m:
                cur_round.append(m)
        ordered_by_round.append(cur_round)
        prev = cur_round

    # Enrich each matchup for display
    rounds_out = []
    for round_matchups in ordered_by_round:
        enriched = []
        for m in round_matchups:
            flip = _display_flips.get(m['id'], False)
            name_a, seed_a = _resolve_card(m, 'a', results_by_id)
            name_b, seed_b = _resolve_card(m, 'b', results_by_id)
            result = results_by_id.get(m['id'])

            if flip:
                left_name,  right_name  = name_b,  name_a
            else:
                left_name,  right_name  = name_a,  name_b

            winner      = result['winner'] if result else None
            left_wins   = (winner == left_name)  if winner else None
            right_wins  = (winner == right_name) if winner else None

            pct_left = pct_right = None
            if result:
                total = result['votes_a'] + result['votes_b']
                if total:
                    va = result['votes_b' if flip else 'votes_a']
                    vb = result['votes_a' if flip else 'votes_b']
                    pct_left  = round(100 * va / total)
                    pct_right = round(100 * vb / total)

            left_info  = _get_card_info(left_name)  if left_name  else {}
            right_info = _get_card_info(right_name) if right_name else {}

            enriched.append({
                'id':             m['id'],
                'round':          m['round'],
                'left_name':      left_name  or 'TBD',
                'left_img_front': left_info.get('img_front'),
                'left_img_back':  left_info.get('img_back'),
                'right_name':     right_name or 'TBD',
                'right_img_front':right_info.get('img_front'),
                'right_img_back': right_info.get('img_back'),
                'winner':         winner,
                'left_wins':      left_wins,
                'right_wins':     right_wins,
                'pct_left':       pct_left,
                'pct_right':      pct_right,
            })
        rounds_out.append(enriched)

    return rounds_out


# Pre-compute the display order once at startup (consistent for all visitors)
_r1_matchups_natural = [m for m in _bracket['matchups'] if m['round'] == 1]
_display_seed = _bracket.get('display_shuffle_seed') or hash(_bracket.get('generated_at', ''))
_display_rng  = random.Random(_display_seed)
_display_r1_order = _shuffle_bracket_tree(_r1_matchups_natural, _display_rng)
_display_flips    = {m['id']: _display_rng.random() < 0.5 for m in _bracket['matchups']}

print(f'Bracket display order computed ({len(_display_r1_order)} R1 matchups).')


# ── Session ────────────────────────────────────────────────────────────────────

def _ensure_session():
    if 'session_id' not in session:
        session['session_id'] = str(uuid.uuid4())


# ── Routes ─────────────────────────────────────────────────────────────────────

ROUND_LABELS = {1: 'Round of 64', 2: 'Round of 32', 3: 'Round of 16',
                4: 'Quarterfinals', 5: 'Semifinals', 6: 'Final'}


@app.route('/')
def index():
    _ensure_session()
    log_page_view('bracket_vote')
    ip  = _client_ip()
    day = _get_current_day()

    if _has_voted(ip, day):
        return render_template('bracket_vote.html', voted=True, day=day)

    results    = _get_results()
    day_matchups = [m for m in _bracket['matchups'] if m['day'] == day]
    if not day_matchups:
        return render_template('bracket_vote.html', voted=False, matchups=[],
                               day=day, round_label='', no_matchups=True)

    round_num   = day_matchups[0]['round']
    round_label = ROUND_LABELS.get(round_num, f'Round {round_num}')

    # Per-user shuffle: matchup order + left/right card orientation
    sid = session.get('session_id', '')
    rng = random.Random(f'{sid}-{day}')

    matchups_ctx = [
        _build_matchup_context(m, results, flip=rng.random() < 0.5)
        for m in day_matchups
    ]

    return render_template('bracket_vote.html', voted=False,
                           matchups=matchups_ctx, day=day,
                           round_label=round_label, no_matchups=False)


@app.route('/api/bracket_submit', methods=['POST'])
def api_bracket_submit():
    _ensure_session()
    ip     = _client_ip()
    device = _detect_device(request.headers.get('User-Agent', ''))
    day    = _get_current_day()

    if _has_voted(ip, day):
        return jsonify({'error': 'already_voted'}), 409

    data      = request.get_json(silent=True) or {}
    votes_raw = data.get('votes', [])   # [{matchup_id, chosen}, ...]

    # Validate: only accept matchup IDs scheduled for today
    day_matchup_ids = {m['id'] for m in _bracket['matchups'] if m['day'] == day}
    results   = _get_results()
    ballot_id = str(uuid.uuid4())
    valid_votes = []
    for v in votes_raw:
        mid = v.get('matchup_id')
        if not isinstance(mid, int) or mid not in day_matchup_ids:
            continue
        chosen = v.get('chosen') or None
        if not chosen:
            continue
        m = _matchup_by_id[mid]
        card_a, _ = _resolve_card(m, 'a', results)
        card_b, _ = _resolve_card(m, 'b', results)
        valid_votes.append((mid, chosen, card_a or '', card_b or ''))

    if not valid_votes:
        return jsonify({'error': 'no_valid_votes'}), 400

    round_ = _matchup_by_id[valid_votes[0][0]]['round']
    _log_votes(ip, day, round_, valid_votes, device, ballot_id)

    return jsonify({'ok': True, 'votes_recorded': len(valid_votes)})


@app.route('/bracket')
def bracket_page():
    _ensure_session()
    log_page_view('bracket_page')
    results       = _get_results()
    rounds_display = _build_bracket_display(results)
    num_rounds    = _bracket['num_rounds']
    round_labels  = [ROUND_LABELS.get(r + 1, f'Round {r + 1}') for r in range(num_rounds)]
    return render_template('bracket_page.html',
                           rounds=rounds_display,
                           round_labels=round_labels,
                           num_rounds=num_rounds)


@app.route('/faq')
def faq():
    _ensure_session()
    log_page_view('faq')
    return render_template('faq.html')


@app.route('/share')
def share():
    return render_template('share.html')


@app.route('/universe')
def universe():
    _ensure_session()
    log_page_view('universe')
    return render_template('universe.html')


@app.route('/stats/<token>')
def stats(token):
    if token != STATS_TOKEN:
        return 'Not found', 404

    # Build day → {round, matchup_count} and round → sorted days from bracket.json
    day_info = {}
    for m in _bracket['matchups']:
        d, r = m['day'], m['round']
        if d not in day_info:
            day_info[d] = {'round': r, 'matchup_count': 0}
        day_info[d]['matchup_count'] += 1

    round_days = {}
    for d, info in day_info.items():
        round_days.setdefault(info['round'], []).append(d)
    for r in round_days:
        round_days[r].sort()

    conn = psycopg2.connect(DATABASE_URL)
    try:
        cur = conn.cursor()

        # Votes per day: total rows and distinct ballots
        cur.execute('''
            SELECT day, COUNT(*) AS total_votes, COUNT(DISTINCT ballot_id) AS ballots
            FROM bracket_votes
            GROUP BY day
            ORDER BY day
        ''')
        day_rows = {d: {'votes': v, 'ballots': b} for d, v, b in cur.fetchall()}

        # Last 24h hourly ballots (ET)
        cur.execute('''
            SELECT
                date_trunc(\'hour\', timestamp::timestamptz AT TIME ZONE \'America/New_York\') AS hour,
                COUNT(DISTINCT ballot_id) AS ballots
            FROM bracket_votes
            WHERE timestamp::timestamptz >= NOW() - INTERVAL \'24 hours\'
            GROUP BY 1
            ORDER BY 1
        ''')
        hourly_rows = cur.fetchall()
    finally:
        conn.close()

    # Build bracket rounds table
    bracket_table = ''
    for d in sorted(day_info.keys()):
        r = day_info[d]['round']
        days_in_round = round_days[r]
        if len(days_in_round) > 1:
            day_within = days_in_round.index(d) + 1
            label = f'{ROUND_LABELS.get(r, f"Round {r}")} \u2014 Day {day_within}'
        else:
            label = ROUND_LABELS.get(r, f'Round {r}')
        data = day_rows.get(d, {'votes': 0, 'ballots': 0})
        bracket_table += (
            f'<tr><td>{label}</td>'
            f'<td style="text-align:right">{data["ballots"]:,}</td>'
            f'<td style="text-align:right">{data["votes"]:,}</td></tr>\n'
        )

    total_ballots = sum(v['ballots'] for v in day_rows.values())
    total_votes   = sum(v['votes']   for v in day_rows.values())

    # Hourly table
    hourly_table = ''
    for hour, ballots in hourly_rows:
        hourly_table += (
            f'<tr><td>{str(hour)[:16]}</td>'
            f'<td style="text-align:right">{ballots:,}</td></tr>\n'
        )

    html = f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Bracket Stats</title>
<style>
body {{ background:#1a1a1a; color:#ddd; font-family:sans-serif; padding:20px; max-width:520px; margin:0 auto; }}
h2 {{ color:#c9a84c; margin:24px 0 8px; }}
table {{ width:100%; border-collapse:collapse; font-size:0.9rem; }}
th {{ text-align:left; color:#888; border-bottom:1px solid #444; padding:4px 8px; }}
td {{ padding:4px 8px; border-bottom:1px solid #2a2a2a; }}
.total {{ color:#c9a84c; font-weight:bold; margin:6px 0 20px; }}
</style>
</head>
<body>
<h2>Top 64 Bracket</h2>
<table>
<tr><th>Round</th><th style="text-align:right">Ballots</th><th style="text-align:right">Total Votes</th></tr>
{bracket_table}
</table>
<p class="total">Total: {total_ballots:,} ballots &nbsp;/&nbsp; {total_votes:,} individual votes</p>

<h2>Last 24 hours (ballots/hour, ET)</h2>
<table>
<tr><th>Hour</th><th style="text-align:right">Ballots</th></tr>
{hourly_table}
</table>
</body>
</html>'''
    return html


# ── Startup ────────────────────────────────────────────────────────────────────

print('Initialising database...')
init_db()
print('Ready. Visit http://127.0.0.1:5000')

if __name__ == '__main__':
    app.run(debug=True, port=5000)
