"""
app_bracket.py — Flask app for the top-64 single-elimination bracket.

Run locally with:
    python app_bracket.py

Then open http://127.0.0.1:5000

Differences from app_top10.py:
  - No Elo system or similarity models
  - Voting is ballot-based: user votes all of today's matchups, then submits once
  - One ballot per IP per round (tracked via bracket_votes table)
  - Bracket structure loaded from bracket.json (generated by generate_bracket.py)
  - bracket_results table records final tallies after advance_bracket.py runs
  - bracket_state table tracks current day
"""

import json
import os
import random
import uuid
from contextlib import contextmanager
from datetime import datetime, timezone

import pandas as pd
import psycopg2
from psycopg2.pool import ThreadedConnectionPool
from dotenv import load_dotenv
from flask import Flask, jsonify, render_template, request, session

load_dotenv()

import sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from parse_data import load_processed_cards

# ── App setup ──────────────────────────────────────────────────────────────────

app = Flask(__name__)
app.secret_key = os.urandom(24)

DATABASE_URL = os.environ.get('DATABASE_URL', '').replace('postgres://', 'postgresql://', 1)
BRACKET_JSON = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'bracket.json')
STATS_TOKEN  = os.environ.get('STATS_TOKEN', 'bracketstats')

_pool = None


@contextmanager
def _get_db():
    conn = _pool.getconn()
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        _pool.putconn(conn)


# ── Database ───────────────────────────────────────────────────────────────────

def _init_pool():
    global _pool
    if not DATABASE_URL:
        raise RuntimeError('DATABASE_URL environment variable is not set.')
    _pool = ThreadedConnectionPool(minconn=1, maxconn=10, dsn=DATABASE_URL)


def init_db():
    _init_pool()
    with _get_db() as conn:
        cur = conn.cursor()

        # One row per individual vote (one IP may cast multiple matchup votes per round)
        cur.execute('''
            CREATE TABLE IF NOT EXISTS bracket_votes (
                id         SERIAL  PRIMARY KEY,
                ballot_id  TEXT    NOT NULL,
                timestamp  TEXT    NOT NULL,
                ip_address TEXT    NOT NULL,
                round      INTEGER NOT NULL,
                day        INTEGER NOT NULL,
                matchup_id INTEGER NOT NULL,
                card_a     TEXT    NOT NULL,
                card_b     TEXT    NOT NULL,
                chosen     TEXT,
                device     TEXT
            )
        ''')
        # Migrate existing tables: add columns added after initial deploy
        for col, defn in [
            ('ballot_id', "TEXT NOT NULL DEFAULT ''"),
            ('card_a',    "TEXT NOT NULL DEFAULT ''"),
            ('card_b',    "TEXT NOT NULL DEFAULT ''"),
        ]:
            cur.execute(f'ALTER TABLE bracket_votes ADD COLUMN IF NOT EXISTS {col} {defn}')
        cur.execute('ALTER TABLE bracket_votes ALTER COLUMN chosen DROP NOT NULL')

        # Final tallies written by advance_bracket.py after voting closes
        cur.execute('''
            CREATE TABLE IF NOT EXISTS bracket_results (
                matchup_id    INTEGER PRIMARY KEY,
                round         INTEGER NOT NULL,
                day           INTEGER NOT NULL,
                bracket_date  TEXT,
                card_a        TEXT    NOT NULL,
                card_b        TEXT    NOT NULL,
                seed_a        INTEGER,
                seed_b        INTEGER,
                votes_a       INTEGER NOT NULL DEFAULT 0,
                votes_b       INTEGER NOT NULL DEFAULT 0,
                winner        TEXT    NOT NULL,
                winner_seed   INTEGER,
                closed_at     TEXT    NOT NULL
            )
        ''')
        cur.execute('ALTER TABLE bracket_results ADD COLUMN IF NOT EXISTS bracket_date TEXT')

        # Personal favorites submitted alongside ballots
        cur.execute('''
            CREATE TABLE IF NOT EXISTS finals_favorite_cards (
                id            SERIAL  PRIMARY KEY,
                timestamp     TEXT    NOT NULL,
                ip_address    TEXT    NOT NULL,
                ballot_id     TEXT,
                card_a        TEXT,
                card_b        TEXT,
                card_c        TEXT,
                response_text TEXT,
                device        TEXT
            )
        ''')

        # Single-row state table
        cur.execute('''
            CREATE TABLE IF NOT EXISTS bracket_state (
                id          INTEGER PRIMARY KEY DEFAULT 1,
                current_day INTEGER NOT NULL DEFAULT 1
            )
        ''')
        cur.execute('''
            INSERT INTO bracket_state (id, current_day)
            VALUES (1, 1)
            ON CONFLICT DO NOTHING
        ''')


def _get_current_day():
    with _get_db() as conn:
        cur = conn.cursor()
        cur.execute('SELECT current_day FROM bracket_state WHERE id = 1')
        row = cur.fetchone()
        return row[0] if row else 1


def _has_voted(ip, day):
    with _get_db() as conn:
        cur = conn.cursor()
        cur.execute(
            'SELECT 1 FROM bracket_votes WHERE ip_address = %s AND day = %s LIMIT 1',
            (ip, day),
        )
        return cur.fetchone() is not None


def _get_user_favorites(ip, day):
    """Return the favorites row for this IP's ballot on the given day, or None."""
    with _get_db() as conn:
        cur = conn.cursor()
        cur.execute(
            '''SELECT f.card_a, f.card_b, f.card_c, f.response_text
               FROM finals_favorite_cards f
               JOIN bracket_votes bv ON bv.ballot_id = f.ballot_id
               WHERE bv.ip_address = %s AND bv.day = %s
               LIMIT 1''',
            (ip, day),
        )
        row = cur.fetchone()
    if not row:
        return None
    return {'card_a': row[0], 'card_b': row[1], 'card_c': row[2], 'response_text': row[3]}


def _get_user_ballot(ip, day):
    """Return the user's ballot for the given day as a list of dicts, ordered by matchup_id.

    Each dict: {matchup_id, card_a, card_b, chosen}
    chosen is None for matchups the user skipped (partial ballot).
    """
    with _get_db() as conn:
        cur = conn.cursor()
        cur.execute(
            'SELECT matchup_id, card_a, card_b, chosen '
            'FROM bracket_votes WHERE ip_address = %s AND day = %s',
            (ip, day),
        )
        rows = cur.fetchall()
    voted = {mid: {'card_a': ca, 'card_b': cb, 'chosen': ch} for mid, ca, cb, ch in rows}

    day_matchups    = sorted([m for m in _bracket['matchups'] if m['day'] == day], key=lambda x: x['id'])
    results_by_id   = _get_results()

    ballot = []
    for m in day_matchups:
        mid = m['id']
        if mid in voted:
            ballot.append({
                'matchup_id': mid,
                'card_a':     voted[mid]['card_a'],
                'card_b':     voted[mid]['card_b'],
                'chosen':     voted[mid]['chosen'],
            })
        else:
            # Skipped matchup — resolve card names from bracket structure
            name_a, _ = _resolve_card(m, 'a', results_by_id)
            name_b, _ = _resolve_card(m, 'b', results_by_id)
            ballot.append({
                'matchup_id': mid,
                'card_a':     name_a or '',
                'card_b':     name_b or '',
                'chosen':     None,
            })

    return ballot


def _log_votes(ip, day, round_, vote_pairs, device, ballot_id):
    """vote_pairs: list of (matchup_id, chosen_name, card_a, card_b)"""
    ts = datetime.now(timezone.utc).isoformat()
    with _get_db() as conn:
        cur = conn.cursor()
        for mid, chosen, card_a, card_b in vote_pairs:
            cur.execute(
                'INSERT INTO bracket_votes '
                '(ballot_id, timestamp, ip_address, round, day, matchup_id, card_a, card_b, chosen, device) '
                'VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)',
                (ballot_id, ts, ip, round_, day, mid, card_a, card_b, chosen, device),
            )


def _get_results():
    with _get_db() as conn:
        cur = conn.cursor()
        cur.execute(
            'SELECT matchup_id, card_a, card_b, seed_a, seed_b, '
            '       votes_a, votes_b, winner, winner_seed '
            'FROM bracket_results'
        )
        rows = cur.fetchall()
    return {
        mid: {
            'card_a': ca, 'card_b': cb, 'seed_a': sa, 'seed_b': sb,
            'votes_a': va, 'votes_b': vb, 'winner': w, 'winner_seed': ws,
        }
        for mid, ca, cb, sa, sb, va, vb, w, ws in rows
    }


def _client_ip():
    # CF-Connecting-IP is set by Cloudflare to the true client IP and cannot be spoofed via XFF
    cf = request.headers.get('CF-Connecting-IP', '').strip()
    if cf:
        return cf
    xff = request.headers.get('X-Forwarded-For', '')
    return xff.split(',')[0].strip() if xff else request.remote_addr


def _detect_device(ua):
    ua = (ua or '').lower()
    return 'mobile' if any(t in ua for t in ('mobile', 'android', 'iphone', 'ipad')) else 'desktop'


def log_page_view(page):
    try:
        ts  = datetime.now(timezone.utc).isoformat()
        ip  = _client_ip()
        sid = session.get('session_id')
        dev = _detect_device(request.headers.get('User-Agent', ''))
        with _get_db() as conn:
            cur = conn.cursor()
            cur.execute(
                'INSERT INTO page_views (timestamp, page, ip_address, session_id, device) '
                'VALUES (%s, %s, %s, %s, %s)',
                (ts, page, ip, sid, dev),
            )
    except Exception:
        pass


# ── Card data ──────────────────────────────────────────────────────────────────

DOUBLE_FACED_LAYOUTS               = {'transform', 'modal_dfc'}
SIDEWAYS_TYPES                     = {'Battle', 'Room'}
SIDEWAYS_LAYOUTS                   = {'split'}
SIDEWAYS_LAYOUT_KEYWORD_EXCLUSIONS = {'Aftermath'}

IMAGE_OVERRIDES = {
    'Sothera, the Supervoid': 'https://cards.scryfall.io/large/front/e/9/e99d6fc0-dcf2-4b25-81c2-02c230a36246.jpg',
    'The Wandering Emperor':  'https://cards.scryfall.io/large/front/f/a/fab2d8a9-ab4c-4225-a570-22636293c17d.jpg',
}

print('Loading bracket.json...')
with open(BRACKET_JSON, encoding='utf-8') as _f:
    _bracket = json.load(_f)

_matchup_by_id = {m['id']: m for m in _bracket['matchups']}
_cards_by_name = {c['name']: c for c in _bracket['cards']}
_all_names     = set(_cards_by_name)

print('Loading card metadata...')
_df   = load_processed_cards()
_meta = _df[_df['name'].isin(_all_names)].drop_duplicates('name').set_index('name')

# ── Personal-pick eligible cards (past 10 years) ───────────────────────────
_PICKS_CUTOFF = '2016-11-12'  # day after Commander 2016 (last set in original bracket)
_eligible_pick_names = sorted(
    _df[pd.to_datetime(_df['released_at']) >= pd.Timestamp(_PICKS_CUTOFF)]['name']
    .dropna().unique().tolist()
)
print(f'Eligible personal-pick cards (post-{_PICKS_CUTOFF}): {len(_eligible_pick_names)}')

# ── Honorable mentions (ranks 65–128, Grief excluded, Growth Spiral inserted at 65) ──
_HONORABLE_MENTIONS_NAMES = [
    'Growth Spiral','Voice of Victory','Quantum Riddler','Overlord of the Balemurk',
    'Mox Amber',"Phlage, Titan of Fire's Fury",'Fury','Wilderness Reclamation',
    'Goldspan Dragon','Mystic Sanctuary','Mayhem Devil','Cut Down','Scute Swarm',
    'Murktide Regent','Faerie Mastermind','Damn','Yavimaya, Cradle of Growth',
    'Seasoned Pyromancer',"Kroxa, Titan of Death's Hunger",'Skyclave Apparition',
    'The Wandering Emperor','Thought Monitor','Farewell','Cauldron Familiar',
    'Undercity Sewers',"Dovin's Veto",'Portal to Phyrexia','The Ozolith',
    "Stormchaser's Talent",'Approach of the Second Sun','Neoform',
    'Liliana, Dreadhorde General','Dryad of the Ilysian Grove','Haywire Mite',
    'Wan Shi Tong, Librarian','Karn, the Great Creator','Soulherder',
    'Veil of Summer','Prismatic Vista','Ketramose, the New Dawn','Ignoble Hierarch',
    "Sheoldred's Edict",'Ocelot Pride','Formidable Speaker','Nissa, Who Shakes the World',
    'Ugin, Eye of the Storms','The Scarab God','Mockingbird',
    'Minsc & Boo, Timeless Heroes','Hydroid Krasis','Elesh Norn, Mother of Machines',
    'Ajani, Nacatl Pariah // Ajani, Nacatl Avenger','Deep-Cavern Bat',
    'Terror of the Peaks','Adeline, Resplendent Cathar','Overlord of the Hauntwoods',
    'Fear of Missing Out','Hostage Taker','Raugrin Triome','Consider',
    'Tolarian Terror','Beseech the Mirror','Leyline Binding',
    'Murderous Rider // Swift End',
]

_HM_META = _df[_df['name'].isin(_HONORABLE_MENTIONS_NAMES)].drop_duplicates('name').set_index('name')

def _hm_meta_get(name, col, default=''):
    try:
        v = _HM_META.at[name, col]
        return default if (isinstance(v, float) and pd.isna(v)) else v
    except KeyError:
        return default

def _build_honorable_mentions():
    cards = []
    for rank, name in enumerate(_HONORABLE_MENTIONS_NAMES, start=65):
        img_front = IMAGE_OVERRIDES.get(name) or str(_hm_meta_get(name, 'img_front') or '')
        img_back  = _hm_meta_get(name, 'img_back', None)
        if isinstance(img_back, float): img_back = None
        layout    = str(_hm_meta_get(name, 'layout', ''))
        is_dfc    = layout in DOUBLE_FACED_LAYOUTS
        released  = _hm_meta_get(name, 'released_at', None)
        try:
            year = int(pd.to_datetime(released).year) if released else None
        except Exception:
            year = None
        cards.append({
            'rank':      rank,
            'name':      name,
            'img_front': img_front or None,
            'img_back':  img_back if is_dfc else None,
            'set_name':  str(_hm_meta_get(name, 'set_name', '')),
            'year':      year,
        })
    return cards

_honorable_mentions_cards = _build_honorable_mentions()
print(f'Honorable mentions: {len(_honorable_mentions_cards)} cards loaded.')

# Full-dataset index for community-favorites card lookups (any card, not just bracket top-64)
_all_cards_meta = _df.drop_duplicates('name').set_index('name')


def _fav_meta_get(name, col, default=None):
    try:
        v = _all_cards_meta.at[name, col]
        return default if (isinstance(v, float) and pd.isna(v)) else v
    except KeyError:
        return default


def _fav_card_info(name):
    """Return image + metadata for any card name, falling back to full dataset if not in bracket."""
    if name in _cards_by_name:
        return _get_card_info(name)
    img_front = _fav_meta_get(name, 'img_front')
    img_back  = _fav_meta_get(name, 'img_back')
    layout    = str(_fav_meta_get(name, 'layout', '') or '')
    released  = _fav_meta_get(name, 'released_at')
    try:
        year = int(pd.to_datetime(released).year) if released else None
    except Exception:
        year = None
    return {
        'img_front': img_front if isinstance(img_front, str) and img_front else None,
        'img_back':  img_back  if (isinstance(img_back, str) and img_back and layout in DOUBLE_FACED_LAYOUTS) else None,
        'set_name':  str(_fav_meta_get(name, 'set_name', '') or ''),
        'year':      year,
    }


def _meta_get(name, col, default=''):
    try:
        v = _meta.at[name, col]
        return default if (isinstance(v, float) and pd.isna(v)) else v
    except KeyError:
        return default


def _is_sideways(name):
    layout    = str(_meta_get(name, 'layout'))
    type_line = str(_meta_get(name, 'type_line'))
    kw        = _meta_get(name, 'keywords', None)
    kw_list   = list(kw) if kw is not None and not isinstance(kw, float) else []
    vintage   = _meta_get(name, 'legal_vintage', 'not_legal') in {'legal', 'restricted'}
    if any(t in type_line for t in SIDEWAYS_TYPES):
        return True
    if layout in SIDEWAYS_LAYOUTS and vintage and not any(k in kw_list for k in SIDEWAYS_LAYOUT_KEYWORD_EXCLUSIONS):
        return True
    return False


_card_info_cache = {}


def _get_card_info(name):
    if name in _card_info_cache:
        return _card_info_cache[name]
    card = _cards_by_name.get(name, {})
    img_front = IMAGE_OVERRIDES.get(name) or card.get('img_front')
    img_back  = card.get('img_back')
    if isinstance(img_front, float): img_front = None
    if isinstance(img_back,  float): img_back  = None
    info = {
        'img_front':   img_front,
        'img_back':    img_back,
        'is_sideways': _is_sideways(name),
        'set_name':    card.get('set_name', ''),
        'year':        card.get('year') or '',
        'seed':        card.get('seed'),
    }
    _card_info_cache[name] = info
    return info


# ── Matchup resolution ─────────────────────────────────────────────────────────

def _resolve_card(matchup, side, results_by_id):
    """Return (name, seed) for 'a' or 'b' side, walking feeder chain for R2+ matchups."""
    if matchup['round'] == 1:
        return matchup[f'name_{side}'], matchup[f'seed_{side}']
    feeder_id = matchup[f'feeder_{side}']
    res = results_by_id.get(feeder_id)
    if res:
        return res['winner'], res['winner_seed']
    return None, None


def _build_matchup_context(matchup, results_by_id, flip):
    """
    Return a template-ready dict for one matchup.
    flip=True swaps which card appears on the left vs right.
    Seeds are intentionally omitted from the returned dict.
    """
    name_a, _ = _resolve_card(matchup, 'a', results_by_id)
    name_b, _ = _resolve_card(matchup, 'b', results_by_id)

    info_a = _get_card_info(name_a) if name_a else {}
    info_b = _get_card_info(name_b) if name_b else {}

    if flip:
        left_name,  right_name  = name_b,  name_a
        left_info,  right_info  = info_b,  info_a
    else:
        left_name,  right_name  = name_a,  name_b
        left_info,  right_info  = info_a,  info_b

    return {
        'id':            matchup['id'],
        'round':         matchup['round'],
        'left_name':     left_name,
        'left_img_front':left_info.get('img_front'),
        'left_img_back': left_info.get('img_back'),
        'left_sideways': left_info.get('is_sideways', False),
        'left_set':      left_info.get('set_name', ''),
        'left_year':     left_info.get('year', ''),
        'right_name':    right_name,
        'right_img_front':right_info.get('img_front'),
        'right_img_back': right_info.get('img_back'),
        'right_sideways': right_info.get('is_sideways', False),
        'right_set':      right_info.get('set_name', ''),
        'right_year':     right_info.get('year', ''),
    }


# ── Bracket page display order ─────────────────────────────────────────────────

def _shuffle_bracket_tree(r1_matchups, rng):
    """
    Recursively shuffle the bracket display order by randomly swapping subtrees
    at each level.  This preserves the tree structure: consecutive pairs in the
    output still correspond to the same R2 matchup, consecutive pairs-of-pairs
    to the same R3 matchup, etc.

    r1_matchups: list of R1 matchup dicts in natural bracket order.
    Returns: flat list of R1 matchup IDs in shuffled display order.
    """
    if len(r1_matchups) == 1:
        return [r1_matchups[0]['id']]

    if len(r1_matchups) == 2:
        a, b = r1_matchups[0]['id'], r1_matchups[1]['id']
        return [b, a] if rng.random() < 0.5 else [a, b]

    mid   = len(r1_matchups) // 2
    left  = _shuffle_bracket_tree(r1_matchups[:mid], rng)
    right = _shuffle_bracket_tree(r1_matchups[mid:], rng)
    return (right + left) if rng.random() < 0.5 else (left + right)


def _build_bracket_display(results_by_id):
    """
    Return a list of rounds, each round being an ordered list of enriched matchup dicts
    ready for the bracket page template.  Uses the pre-computed display order and flips.
    """
    # Build feeder-set → matchup lookup for R2+ matchups
    feeder_lookup = {}
    for m in _bracket['matchups']:
        if m['round'] > 1:
            feeder_lookup[frozenset({m['feeder_a'], m['feeder_b']})] = m

    # Derive ordered matchup lists for each round from the shuffled R1 order
    r1_by_id = {m['id']: m for m in _bracket['matchups'] if m['round'] == 1}
    ordered_by_round = [[r1_by_id[mid] for mid in _display_r1_order]]
    top_feeder_by_matchup_id = {}  # matchup_id → feeder_id displayed on top

    prev = ordered_by_round[0]
    for _ in range(2, _bracket['num_rounds'] + 1):
        cur_round = []
        for i in range(0, len(prev), 2):
            key = frozenset({prev[i]['id'], prev[i + 1]['id']})
            m   = feeder_lookup.get(key)
            if m:
                cur_round.append(m)
                top_feeder_by_matchup_id[m['id']] = prev[i]['id']
        ordered_by_round.append(cur_round)
        prev = cur_round

    # Enrich each matchup for display
    rounds_out = []
    for round_matchups in ordered_by_round:
        enriched = []
        for m in round_matchups:
            name_a, seed_a = _resolve_card(m, 'a', results_by_id)
            name_b, seed_b = _resolve_card(m, 'b', results_by_id)

            if m['round'] == 1:
                flip = _display_flips.get(m['id'], False)
            else:
                # Winner of the top-displayed feeder goes on top
                top_feeder_id = top_feeder_by_matchup_id.get(m['id'])
                flip = (m.get('feeder_b') == top_feeder_id)
            result = results_by_id.get(m['id'])

            if flip:
                left_name,  right_name  = name_b,  name_a
                left_seed,  right_seed  = seed_b,  seed_a
            else:
                left_name,  right_name  = name_a,  name_b
                left_seed,  right_seed  = seed_a,  seed_b

            winner      = result['winner'] if result else None
            left_wins   = (winner == left_name)  if winner else None
            right_wins  = (winner == right_name) if winner else None

            pct_left = pct_right = None
            if result:
                total = result['votes_a'] + result['votes_b']
                if total:
                    va = result['votes_b' if flip else 'votes_a']
                    vb = result['votes_a' if flip else 'votes_b']
                    pct_left  = round(100 * va / total, 1)
                    pct_right = round(100 * vb / total, 1)

            left_info  = _get_card_info(left_name)  if left_name  else {}
            right_info = _get_card_info(right_name) if right_name else {}

            enriched.append({
                'id':             m['id'],
                'round':          m['round'],
                'left_name':      left_name  or 'TBD',
                'left_seed':      left_seed,
                'left_img_front': left_info.get('img_front'),
                'left_img_back':  left_info.get('img_back'),
                'right_name':     right_name or 'TBD',
                'right_seed':     right_seed,
                'right_img_front':right_info.get('img_front'),
                'right_img_back': right_info.get('img_back'),
                'winner':         winner,
                'left_wins':      left_wins,
                'right_wins':     right_wins,
                'pct_left':       pct_left,
                'pct_right':      pct_right,
            })
        rounds_out.append(enriched)

    return rounds_out


# Pre-compute the display order once at startup (consistent for all visitors)
_r1_matchups_natural = [m for m in _bracket['matchups'] if m['round'] == 1]
_display_seed = _bracket.get('display_shuffle_seed') or hash(_bracket.get('generated_at', ''))
_display_rng  = random.Random(_display_seed)
_display_r1_order = _shuffle_bracket_tree(_r1_matchups_natural, _display_rng)
_display_flips    = {m['id']: _display_rng.random() < 0.5 for m in _bracket['matchups']}

print(f'Bracket display order computed ({len(_display_r1_order)} R1 matchups).')


# ── Template globals ───────────────────────────────────────────────────────────

@app.context_processor
def inject_pick_names():
    return {'pick_names': _eligible_pick_names}


# ── Session ────────────────────────────────────────────────────────────────────

def _ensure_session():
    if 'session_id' not in session:
        session['session_id'] = str(uuid.uuid4())


# ── Routes ─────────────────────────────────────────────────────────────────────

ROUND_LABELS = {1: 'Round of 64', 2: 'Round of 32', 3: 'Round of 16',
                4: 'Quarterfinals', 5: 'Semifinals', 6: 'Final'}


@app.route('/')
def index():
    _ensure_session()
    log_page_view('bracket_vote')
    winner_img = None
    try:
        info = _fav_card_info("Urza's Saga")
        winner_img = info.get('img_front')
    except Exception:
        pass
    return render_template('bracket_vote.html', winner_img=winner_img)


@app.route('/api/bracket_submit', methods=['POST'])
def api_bracket_submit():
    _ensure_session()
    ip     = _client_ip()
    device = _detect_device(request.headers.get('User-Agent', ''))
    day    = _get_current_day()

    if _has_voted(ip, day):
        return jsonify({'error': 'already_voted'}), 409

    data      = request.get_json(silent=True) or {}
    votes_raw = data.get('votes', [])   # [{matchup_id, chosen}, ...]

    # Validate: only accept matchup IDs scheduled for today
    day_matchup_ids = {m['id'] for m in _bracket['matchups'] if m['day'] == day}
    results   = _get_results()
    ballot_id = str(uuid.uuid4())
    valid_votes = []
    for v in votes_raw:
        mid = v.get('matchup_id')
        if not isinstance(mid, int) or mid not in day_matchup_ids:
            continue
        chosen = v.get('chosen') or None
        if not chosen:
            continue
        m = _matchup_by_id[mid]
        card_a, _ = _resolve_card(m, 'a', results)
        card_b, _ = _resolve_card(m, 'b', results)
        valid_votes.append((mid, chosen, card_a or '', card_b or ''))

    if not valid_votes:
        return jsonify({'error': 'no_valid_votes'}), 400

    round_ = _matchup_by_id[valid_votes[0][0]]['round']
    _log_votes(ip, day, round_, valid_votes, device, ballot_id)

    # Personal favorites (optional — included in same submission as the ballot)
    pick_set = set(_eligible_pick_names)
    picks = []
    for i in range(1, 4):
        p = data.get(f'pick_{i}')
        picks.append(p if (p and p in pick_set) else None)
    # Parameterised query handles all escaping; strip + cap length server-side as well
    response_text = (data.get('comment') or '').strip()[:500] or None

    if any(picks) or response_text:
        ts = datetime.now(timezone.utc).isoformat()
        with _get_db() as conn:
            cur = conn.cursor()
            cur.execute(
                'INSERT INTO finals_favorite_cards '
                '(timestamp, ip_address, ballot_id, card_a, card_b, card_c, response_text, device) '
                'VALUES (%s, %s, %s, %s, %s, %s, %s, %s)',
                (ts, ip, ballot_id, picks[0], picks[1], picks[2], response_text, device),
            )

    return jsonify({'ok': True, 'votes_recorded': len(valid_votes)})


@app.route('/bracket')
def bracket_page():
    _ensure_session()
    log_page_view('bracket_page')
    results       = _get_results()
    rounds_display = _build_bracket_display(results)
    num_rounds    = _bracket['num_rounds']
    round_labels  = [ROUND_LABELS.get(r + 1, f'Round {r + 1}') for r in range(num_rounds)]
    return render_template('bracket_page.html',
                           rounds=rounds_display,
                           round_labels=round_labels,
                           num_rounds=num_rounds)


@app.route('/faq')
def faq():
    _ensure_session()
    log_page_view('faq')
    return render_template('faq.html')


@app.route('/share')
def share():
    return render_template('share.html')


@app.route('/universe')
def universe():
    _ensure_session()
    log_page_view('universe')
    return render_template('universe.html')


@app.route('/honorable-mentions')
def honorable_mentions():
    _ensure_session()
    log_page_view('honorable_mentions')
    return render_template('honorable_mentions.html', cards=_honorable_mentions_cards)


@app.route('/community-favorites')
def community_favorites():
    _ensure_session()
    log_page_view('community_favorites')

    # Initialise per-session shuffle state
    if 'fav_seed' not in session:
        session['fav_seed'] = random.randint(0, 2 ** 31)
        session['fav_pos']  = 0

    # Advance position when the "see more" button is clicked
    if request.args.get('next') == '1':
        session['fav_pos'] = session.get('fav_pos', 0) + 1
        session.modified = True

    pos  = session.get('fav_pos', 0)
    seed = session['fav_seed']

    # Load all submitted favorites from DB
    with _get_db() as conn:
        cur = conn.cursor()
        cur.execute(
            'SELECT id, card_a, card_b, card_c, response_text '
            'FROM finals_favorite_cards ORDER BY id'
        )
        all_rows = cur.fetchall()

    if not all_rows:
        return render_template('community_favorites.html', entry=None, pos=0, total=0)

    # Split: rich = has response_text AND at least one non-null card name
    rich, sparse = [], []
    for row in all_rows:
        rid, ca, cb, cc, rt = row
        has_text = bool(rt and rt.strip())
        has_card = any(c for c in [ca, cb, cc] if c)
        if has_text and has_card:
            rich.append(row)
        else:
            sparse.append(row)

    # Deterministic shuffle using per-session seed
    rng = random.Random(seed)
    rng.shuffle(rich)
    rng.shuffle(sparse)

    # Interleave: rich[0], sparse[0], rich[1], sparse[1], ...
    merged = []
    ri = si = 0
    while ri < len(rich) or si < len(sparse):
        if ri < len(rich):
            merged.append(rich[ri]); ri += 1
        if si < len(sparse):
            merged.append(sparse[si]); si += 1

    row = merged[pos % len(merged)]
    rid, ca, cb, cc, rt = row

    # Build card dicts for cards that have images
    cards = []
    for name in [ca, cb, cc]:
        if not name:
            continue
        info = _fav_card_info(name)
        if info.get('img_front'):
            cards.append({
                'name':      name,
                'img_front': info['img_front'],
                'img_back':  info.get('img_back'),
                'set_name':  info.get('set_name', ''),
                'year':      info.get('year'),
            })

    entry = {
        'cards':         cards,
        'response_text': rt.strip() if rt else None,
    }

    return render_template('community_favorites.html', entry=entry,
                           pos=pos, total=len(merged))


@app.route('/stats/<token>')
def stats(token):
    if token != STATS_TOKEN:
        return 'Not found', 404

    # Build day → {round, matchup_count} and round → sorted days from bracket.json
    day_info = {}
    for m in _bracket['matchups']:
        d, r = m['day'], m['round']
        if d not in day_info:
            day_info[d] = {'round': r, 'matchup_count': 0}
        day_info[d]['matchup_count'] += 1

    round_days = {}
    for d, info in day_info.items():
        round_days.setdefault(info['round'], []).append(d)
    for r in round_days:
        round_days[r].sort()

    conn = psycopg2.connect(DATABASE_URL)
    try:
        cur = conn.cursor()

        # Votes per day: total rows and distinct ballots
        cur.execute('''
            SELECT day, COUNT(*) AS total_votes, COUNT(DISTINCT ballot_id) AS ballots
            FROM bracket_votes
            GROUP BY day
            ORDER BY day
        ''')
        day_rows = {d: {'votes': v, 'ballots': b} for d, v, b in cur.fetchall()}

        # Last 24h hourly ballots (ET)
        cur.execute('''
            SELECT
                date_trunc(\'hour\', timestamp::timestamptz AT TIME ZONE \'America/New_York\') AS hour,
                COUNT(DISTINCT ballot_id) AS ballots
            FROM bracket_votes
            WHERE timestamp::timestamptz >= NOW() - INTERVAL \'24 hours\'
            GROUP BY 1
            ORDER BY 1
        ''')
        hourly_rows = cur.fetchall()
    finally:
        conn.close()

    # Build bracket rounds table
    bracket_table = ''
    for d in sorted(day_info.keys()):
        r = day_info[d]['round']
        days_in_round = round_days[r]
        if len(days_in_round) > 1:
            day_within = days_in_round.index(d) + 1
            label = f'{ROUND_LABELS.get(r, f"Round {r}")} \u2014 Day {day_within}'
        else:
            label = ROUND_LABELS.get(r, f'Round {r}')
        data = day_rows.get(d, {'votes': 0, 'ballots': 0})
        bracket_table += (
            f'<tr><td>{label}</td>'
            f'<td style="text-align:right">{data["ballots"]:,}</td>'
            f'<td style="text-align:right">{data["votes"]:,}</td></tr>\n'
        )

    total_ballots = sum(v['ballots'] for v in day_rows.values())
    total_votes   = sum(v['votes']   for v in day_rows.values())

    # Hourly table
    hourly_table = ''
    for hour, ballots in hourly_rows:
        hourly_table += (
            f'<tr><td>{str(hour)[:16]}</td>'
            f'<td style="text-align:right">{ballots:,}</td></tr>\n'
        )

    html = f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Bracket Stats</title>
<style>
body {{ background:#1a1a1a; color:#ddd; font-family:sans-serif; padding:20px; max-width:520px; margin:0 auto; }}
h2 {{ color:#c9a84c; margin:24px 0 8px; }}
table {{ width:100%; border-collapse:collapse; font-size:0.9rem; }}
th {{ text-align:left; color:#888; border-bottom:1px solid #444; padding:4px 8px; }}
td {{ padding:4px 8px; border-bottom:1px solid #2a2a2a; }}
.total {{ color:#c9a84c; font-weight:bold; margin:6px 0 20px; }}
</style>
</head>
<body>
<h2>Top 64 Bracket</h2>
<table>
<tr><th>Round</th><th style="text-align:right">Ballots</th><th style="text-align:right">Total Votes</th></tr>
{bracket_table}
</table>
<p class="total">Total: {total_ballots:,} ballots &nbsp;/&nbsp; {total_votes:,} individual votes</p>

<h2>Last 24 hours (ballots/hour, ET)</h2>
<table>
<tr><th>Hour</th><th style="text-align:right">Ballots</th></tr>
{hourly_table}
</table>
</body>
</html>'''
    return html


@app.route('/vote-counts')
def vote_counts():
    base_dir = os.path.dirname(os.path.abspath(__file__))

    # Load queues.json for queue sizes (best-effort); exclude queue 1 (test queue)
    queues_json_path = os.path.join(base_dir, 'queues.json')
    try:
        with open(queues_json_path, encoding='utf-8') as f:
            _qdata = json.load(f)
        queues_meta = {q['id']: q for q in _qdata.get('queues', [])
                       if q['id'] != 1}
    except Exception:
        queues_meta = {}

    # Load top_10_queue.json for top-10% queue size (best-effort)
    top10_json_path = os.path.join(base_dir, 'top_10_queue.json')
    try:
        with open(top10_json_path, encoding='utf-8') as f:
            _t10 = json.load(f)
        top10_size = _t10.get('total_cards') or len(_t10.get('cards', []))
    except Exception:
        top10_size = None

    with _get_db() as conn:
        cur = conn.cursor()

        # ── Bracket section ────────────────────────────────────────────────────
        cur.execute('''
            SELECT day, COUNT(*) AS total_votes, COUNT(DISTINCT ballot_id) AS ballots
            FROM bracket_votes
            GROUP BY day
            ORDER BY day
        ''')
        day_rows = {d: {'votes': v, 'ballots': b} for d, v, b in cur.fetchall()}

        # ── Regular queue section (exclude queue 1) ────────────────────────────
        cur.execute('''
            SELECT queue_id, COUNT(*) AS votes
            FROM votes
            WHERE queue_id IS NOT NULL AND queue_id != 1
            GROUP BY queue_id
            ORDER BY queue_id
        ''')
        queue_vote_rows = {qid: v for qid, v in cur.fetchall()}

        # ── Top-10% section ────────────────────────────────────────────────────
        cur.execute('SELECT COUNT(*) FROM votes_top10')
        top10_votes = cur.fetchone()[0]

    # ── Build bracket table ────────────────────────────────────────────────────
    day_info = {}
    for m in _bracket['matchups']:
        d, r = m['day'], m['round']
        if d not in day_info:
            day_info[d] = {'round': r}

    round_days = {}
    for d, info in day_info.items():
        round_days.setdefault(info['round'], []).append(d)
    for r in round_days:
        round_days[r].sort()

    bracket_rows_html = ''
    for d in sorted(day_info.keys()):
        r = day_info[d]['round']
        days_in_round = round_days[r]
        if len(days_in_round) > 1:
            day_within = days_in_round.index(d) + 1
            label = f'{ROUND_LABELS.get(r, f"Round {r}")} \u2014 Day {day_within}'
        else:
            label = ROUND_LABELS.get(r, f'Round {r}')
        data = day_rows.get(d, {'votes': 0, 'ballots': 0})
        bracket_rows_html += (
            f'<tr><td>{label}</td>'
            f'<td class="num">{data["ballots"]:,}</td>'
            f'<td class="num">{data["votes"]:,}</td></tr>\n'
        )

    total_ballots = sum(v['ballots'] for v in day_rows.values())
    total_votes   = sum(v['votes']   for v in day_rows.values())

    # ── Build queue table ──────────────────────────────────────────────────────
    all_qids = sorted(set(list(queues_meta.keys()) + list(queue_vote_rows.keys())))
    queue_rows_html = ''
    for qid in all_qids:
        votes  = queue_vote_rows.get(qid, 0)
        q_meta = queues_meta.get(qid, {})
        qsize  = len(q_meta.get('cards', [])) if q_meta else None
        qsize_str = f'{qsize:,}' if qsize is not None else '—'
        queue_rows_html += (
            f'<tr><td>Queue {qid}</td>'
            f'<td class="num">{qsize_str}</td>'
            f'<td class="num">{votes:,}</td></tr>\n'
        )

    queue_total_votes = sum(queue_vote_rows.values())

    top10_size_str = f'{top10_size:,}' if top10_size is not None else '—'

    html = f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Vote Counts — Magic Bracket</title>
<style>
* {{ box-sizing: border-box; margin: 0; padding: 0; }}
body {{ background: #1a1a1a; color: #ddd; font-family: sans-serif; }}
nav {{
  display: flex; justify-content: center; gap: 2rem;
  padding: 0.75rem 1rem;
  background: #13132a; border-bottom: 1px solid #2a2a4a;
  flex-wrap: wrap;
}}
nav a {{ color: #c8a96e; text-decoration: none; font-size: 0.85rem; letter-spacing: 0.03em; }}
nav a:hover {{ text-decoration: underline; }}
.page-header {{
  background: #111; padding: 14px 20px 12px;
  border-bottom: 1px solid #2a2a2a;
  text-align: center;
}}
.page-header h1 {{
  font-family: Georgia, serif;
  font-size: 1.4rem; color: #c9a84c;
  letter-spacing: 0.12em; text-transform: uppercase; font-weight: normal;
}}
.content {{ padding: 24px 20px; max-width: 560px; margin: 0 auto; }}
h2 {{ color: #c9a84c; margin: 28px 0 10px; font-size: 1.05rem; letter-spacing: 0.05em; text-transform: uppercase; font-weight: normal; }}
h2:first-child {{ margin-top: 0; }}
table {{ width: 100%; border-collapse: collapse; font-size: 0.88rem; }}
th {{ text-align: left; color: #888; border-bottom: 1px solid #444; padding: 5px 10px; font-weight: normal; }}
td {{ padding: 5px 10px; border-bottom: 1px solid #222; }}
td.num {{ text-align: right; font-variant-numeric: tabular-nums; }}
th.num {{ text-align: right; }}
.total {{ color: #c9a84c; font-weight: bold; margin: 8px 0 0; font-size: 0.88rem; }}
</style>
</head>
<body>

<nav>
  <a href="/">Home</a>
  <a href="/bracket">Full Bracket</a>
  <a href="/honorable-mentions">Honorable Mentions</a>
  <a href="/community-favorites">Community Favorites</a>
  <a href="/universe">Card Browser</a>
  <a href="/vote-counts">Vote Counts</a>
  <a href="/faq">FAQ</a>
  <a href="/share">Share</a>
</nav>

<div class="page-header">
  <h1>Vote Counts</h1>
</div>

<div class="content">

<h2>Top 64 Bracket</h2>
<table>
  <tr><th>Round</th><th class="num">Ballots</th><th class="num">Total Votes</th></tr>
  {bracket_rows_html}
</table>
<p class="total">Total: {total_ballots:,} ballots &nbsp;/&nbsp; {total_votes:,} individual votes</p>

<h2>Top 10% Tournament</h2>
<table>
  <tr><th>Phase</th><th class="num">Cards</th><th class="num">Votes</th></tr>
  <tr><td>Tournament</td><td class="num">{top10_size_str}</td><td class="num">{top10_votes:,}</td></tr>
</table>

<h2>Regular Queues</h2>
<table>
  <tr><th>Queue</th><th class="num">Cards</th><th class="num">Votes</th></tr>
  {queue_rows_html}
</table>
<p class="total">Total: {queue_total_votes:,} votes</p>

</div>
</body>
</html>'''
    return html


# ── Startup ────────────────────────────────────────────────────────────────────

print('Initialising database...')
init_db()
print('Ready. Visit http://127.0.0.1:5000')

if __name__ == '__main__':
    app.run(debug=True, port=5000)
